### ISSUE TITLE
More detail in README

### ISSUE THREAD

**Issue by omidb** [RealScout/deep-learning-images#1]
Hi,

Thanks for sharing this. Would you please add more detailed steps in README to how use this. I have no idea what Packer is and where should I start.

**Comment by graphaelli** [comment]
@omidb check out the updated https://github.com/RealScout/deep-learning-images/blob/master/README.md#step-0 to see if that helps.  If you prefer not to use packer, https://github.com/RealScout/deep-learning-images/blob/master/install/tensorflow.sh should be a useful guide for a tensorflow install on a g2.\* EC2 instance with CUDA and cuDNN libs installed.
