### ISSUE TITLE
Tensorflow configuration error

### ISSUE THREAD

**Issue by lpatruno** [RealScout/deep-learning-images#7]
When I import tensorflow in the Python interpreter it is unable to load cuDNN. Here is the output:

```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3448] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
```

**Comment by lpatruno** [comment]
Hmm. I think I may have messed something up on this one when trying to combine the `base.json` and tensorflow packer files into a single file. If I run the two separately, I don't have the same error. I will close this for now.

**Comment by lpatruno** [comment]
Apologies. I was mistaken. When I create a new instance, even after following the directions listed here, I get the same error. Any ideas?

**Comment by lpatruno** [comment]
This error is corrected if I follow both of these steps, FYI....

This
http://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx#answer-20357035

plus this
http://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx#answer-37874347

= this
```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
```

**Comment by lpatruno** [comment]
Any word on this?

**Comment by graphaelli** [comment]
I haven't had a chance to look, hopefully in the next week or so

**Comment by graphaelli** [comment]
1da02a7055e275bc63c1c45a85057af2011a54f8 should resolve this.  Unfortunately, that requires base image rebuilds.

**Comment by lpatruno** [comment]
Thanks, @graphaelli . I'll have a look.

**Comment by lpatruno** [comment]
Checked and this works. Thanks!
